name: Allocations

on:
  push:
    branches:
      - develop
      - 'feature/**'
      - 'bugfix/**'

jobs:
  allocations:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        julia-version: [1.7, 'nightly']
        julia-arch: [x64]

    steps:
      - uses: actions/checkout@v2
      - name: "Set up Julia"
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}
      - name: "Run test"
        run: |
          julia --project=@. -e "using Pkg; Pkg.instantiate(); Pkg.build()"
          julia -O3 --project=@. test/allocation_tests.jl
