name: Benchmarks

on:
  pull_request:
    branches-ignore:
    - 'doc/**'

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  run:
    if: ${{ !startsWith(github.head_ref, 'compathelper/') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: julia-actions/setup-julia@v3
        with:
          version: 1.11
          # fails with newer versions; probably related to BenchmarkCI not supporting them yet
      - uses: julia-actions/cache@v3
      - uses: julia-actions/julia-buildpkg@v1
      - name: Install dependencies
        run: julia -e 'using Pkg; pkg"add PkgBenchmark BenchmarkTools BenchmarkCI@0.1"'
      - name: Run benchmarks
        run: julia -e 'using BenchmarkCI; BenchmarkCI.judge(baseline="origin/develop"); BenchmarkCI.displayjudgement()'

      # generate result markdown
      - name: generate benchmark result
        id: generate-result-markdown
        run: |
          {
            echo 'body<<BENCHMARK_RESULT_EOF'
            julia -tauto -e '
            using BenchmarkCI
            let
                judgement = BenchmarkCI._loadjudge(BenchmarkCI.DEFAULT_WORKSPACE)
                title = "Benchmark result"
                ciresult = BenchmarkCI.CIResult(; judgement, title)
                BenchmarkCI.printcommentmd(stdout::IO, ciresult)
            end
            '
            echo 'BENCHMARK_RESULT_EOF'
          } >> "$GITHUB_OUTPUT"
      # check if the previous comment exists (only for non-fork PRs that have write access)
      - name: find comment
        if: ${{ github.event.pull_request.head.repo.full_name == github.repository && github.actor != 'dependabot[bot]' }}
        uses: peter-evans/find-comment@v4
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Benchmark result

      # create/update comment
      - name: create comment
        if: ${{ steps.fc.outputs.comment-id == 0 && github.actor != 'dependabot[bot]' && github.event.pull_request.head.repo.full_name == github.repository }}
        uses: peter-evans/create-or-update-comment@v5
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: ${{ steps.generate-result-markdown.outputs.body }}
      - name: update comment
        if: ${{ steps.fc.outputs.comment-id != 0 && github.actor != 'dependabot[bot]' && github.event.pull_request.head.repo.full_name == github.repository }}
        uses: peter-evans/create-or-update-comment@v5
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          body: ${{ steps.generate-result-markdown.outputs.body }}
