name: Documentation

on:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request:
    branches-ignore:
      - 'dependabot/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.7'
      - uses: julia-actions/cache@v1
      - name: Install dependencies
        run: |
          export JULIA_PROJECT=@.
          export JULIA_MPIEXEC=/tmp/mpiexecwrapper
          echo -e '#!/bin/bash\nmpiexec --allow-run-as-root $@' > $JULIA_MPIEXEC
          chmod +x $JULIA_MPIEXEC
          julia -e 'println(ENV)'
          julia -e 'using Pkg; Pkg.instantiate(); Pkg.build()'
          julia --project=docs/ -e 'using Pkg; Pkg.instantiate()'
          julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
          julia --project=docs/ -e 'using Rimu'
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: julia --project=docs/ docs/make.jl
