name: Documentation

on:
  push:
    branches:
      - master
      - develop
      - feature/github-actions
      - 'feature/doc-**'
    tags: '*'
  pull_request:
    branches:
      - master
      - develop
      - feature/github-actions
      - 'feature/doc-**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1.6'
      # - name: "Install MPI"
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y openmpi-bin libopenmpi-dev
      - name: Install dependencies
        run: |
          export JULIA_PROJECT=@.
          export JULIA_MPIEXEC=/tmp/mpiexecwrapper
          echo -e '#!/bin/bash\nmpiexec --allow-run-as-root $@' > $JULIA_MPIEXEC
          chmod +x $JULIA_MPIEXEC
          julia -e 'println(ENV)'
          julia -e 'using Pkg; Pkg.instantiate(); Pkg.build()'
          julia --project=docs/ -e 'using Pkg; Pkg.instantiate()'
          julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
          julia --project=docs/ -e 'using Rimu'
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: julia --project=docs/ docs/make.jl
